name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  Linux:
    name: ${{ matrix.name }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        config: [Debug, Release]
        include:
          - os: ubuntu-20.04
            name: Linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 10

      - name: Dependencies
        run: sudo apt-get install ccache

      - name: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.8

      - name: Cache Build
        id: cache-build
        uses: actions/cache@v3.2.6
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ matrix.config }}-cache

      - name: Prepare ccache
        run: |
          ccache --max-size=1.0G
          ccache -V && ccache --show-stats && ccache --zero-stats

      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DEIGEN_CUDA_EXAMPLE_BUILD_TESTS=ON \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build
        run: cd build; make -j2; ccache --show-stats

      - name: Tests
        run: cd build; ctest --verbose

      - name: Benchmark
        run: cd build; ./tests/eigen_cuda_example_tests '[!benchmark]'
